application: udacity-cs253-italianidle
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /wiki(/_edit)?/(?:[a-zA-Z0-9_-]+/?)*
  script: wiki.app
- url: /blog(/?|/(newpost|(\d+)|signup|welcome|login|logout|flush))
  script: blog.app
- url: /blog/(\d+)?.json
  script: blog.app
- url: /asciichan
  script: asciichan.app
- url: /unit2/rot13
  script: rot13.app
- url: /unit2/(signup|welcome)
  script: signup.app
- url: /.*
  script: main.app
