application: udacity-cs253-italianidle
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /unit2/rot13
  script: rot13.app
- url: /unit2/(signup|welcome)
  script: signup.app
- url: /.*
  script: main.app
